---
- hosts: all
  become: yes
  tasks:
    - name: List installed packages
      package_facts:
      register: package_list

    - name: Display package list
      debug:
        var: package_list.ansible_facts.packages
